global_costmap:

  map_type: costmap
  track_unknown_space: true
  unknown_cost_value: 255
  obstacle_range: 2.5
  raytrace_range: 3.0


  inflation_radius: 0.5
  #transform_tolerance: 0.5
  inscribed_radius: 0.31
  circumscribed_radius: 0.33

  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 0.5
  publish_frequency: 0.1
  static_map: true
  rolling_window: false

  #Investigate what this actually does
  cost_scaling_factor: 10.0
